print("Анализ последовательности ДНК")
dna = input("Будьте так любезны, ведите  последовательность ДНК➝ ")
print("Всевышний говорит:")
print(dna.count("A"))
print(dna.count("T"))
print(dna.count("G"))
print(dna.count("C"))
F = dna.count("A")+dna.count("T")+dna.count("G")+dna.count("C")
print(f"Общая сумма нуклеотидов =", F)