services:
  postgres:
    image: postgres:16

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"