fio=input("Извольте сообщить ФИО исследователя: ")
date=input("Дата: ")
exp_name=input("Название эксперимента: ")
concl=input("Вывод: ")
with open("journal.txt", "w", encoding="utf-8") as report:
    report.write(f"+--------------------------------------------------+\n")
    report.write(f"| Электронный лабораторный журнал\n+--------------------------------------------------+\n")
    report.write(f"| ФИО исследователя: {fio} \n")
    report.write(f"| Дата: {date} \n")
    report.write(f"| Название эксперимента: {exp_name} \n")
    report.write(f"+--------------------------------------------------+\n")
    report.write(f"| Вывод: {concl} \n")
    report.write(f"+--------------------------------------------------+\n")